if HAVE_QDMA_TCP
_qdma_tcp_files = \
	prov/qdma_tcp/src/qdma_tcp.c \
	prov/qdma_tcp/src/qdma_tcp.h

# NOTE:
# qdma_tcp currently depends on internal tcp provider symbols (xnet_util_prov),
# which are not available when tcp is built as a DSO. We therefore only build
# qdma_tcp as a built-in provider (part of libfabric), not as a plugin.
src_libfabric_la_SOURCES += $(_qdma_tcp_files)

prov_dist_man_pages += man/man7/fi_qdma_tcp.7

endif HAVE_QDMA_TCP
